"use client"
import React, { useState } from 'react'
import TextInput from "@/components/FormInputs/TextInput";
import TextareaInput from "@/components/FormInputs/TextareaInput";
import ImageInput from "@/components/FormInputs/ImageInput"
import SubmitButton from '@/components/FormInputs/SubmitButton'
import { makePostRequest, makePutRequest } from "@/lib/apiRequest";
import generateSlug from '@/lib/generateSlug'
import generateCouponCode from '@/lib/generateCouponCode'
import generateIsoFormattedDate from '@/lib/generateIsoFormattedDate'
import FormHeader from '@/components/backoffice/FoarmHeader'
import {useForm} from 'react-hook-form'
import { useRouter } from 'next/navigation';
import ToggleInput from "@/components/FormInputs/ToggleInput"
import ImageUpload from "@/components/FormInputs/ImageUpload"


export default function NewBanner() {

  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);
  
  const {register,reset,watch,handleSubmit,formState:{errors}}= useForm({
    defaultValues:{
        isActive:true
    }
  });
  const router = useRouter();
  function redirect(){
    router.push('/dashboard/banners');
  }

  const isActive = watch("isActive");
  async function onSubmit(data) {
  {/* 
      id = autogenerated
      title
      code= autogenerated
      description
      validity date
      */}

  

   data.imageUrl = imageUrl;
   data.isActive = isActive;
   console.log("ImageUrl= "+data.imageUrl);
   makePostRequest(
    setLoading,
    "api/banners",
    data,
    "Banner",
    reset,
    redirect
  )
  setImageUrl("");
    // if (isUpdate) {
    //   // Update request
    //   makePutRequest(
    //     setLoading,
    //     `api/categories/${initialData.id}`,
    //     data,
    //     "Category",
    //     redirect,
    //     reset
    //   );
    // } else {
    //   makePostRequest(setLoading, "api/categories", data, "Category", reset);
    // }
  }
  return (
    <div>
     
    
      <FormHeader title="New Coupon"/>
       {/* Form */}
       <form
        onSubmit={handleSubmit(onSubmit)}
        className="w-full max-w-4xl p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-700 dark:border-gray-700 mx-auto my-3"
      >
        <div className="grid gap-4 sm:grid-cols-2 sm:gap-6">
          <TextInput
            label="Banner Title"
            name="title"
            register={register}
            errors={errors}
            className="w-full"
          />
        
           <TextInput
            label="Domain Name"
            name="link"
            register={register}
            errors={errors}
            className="w-full"
          />
          <ImageUpload
            imageUrl={imageUrl}
            setImageUrl={setImageUrl}
            label="Banner Image"
           />
          <ToggleInput
            label="Publish your Banner"
            name="isActive"
            trueTitle="Active"
            falseTitle="Draft"
            register={register}
            errors={errors}
            />
        </div>
        <SubmitButton
          isLoading={loading}
          buttonTitle="Create Banner"
          loadingButtonTitle="Creating Banner please wait..."
        />
      </form>

    </div>
  )
}
